apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    name: django-app
    instance: django-py
    component: cron
    part-of: k8s-test-django
    managed-by: kubectl
spec:
  schedule: "0 15 1 * *"
  timeZone: "Europe/Moscow"
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: clearsessions
              image: django_app
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: django-secret
              command: ["python", "manage.py", "clearsessions"]