apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/instance: django-py
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: k8s-test-django
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: django-app
    app.kubernetes.io/instance: django-py
    app.kubernetes.io/component: web
  ports:
    - port: 80