apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  labels:
    name: django-app
    instance: django-py
    component: migrate
    part-of: k8s-test-django
    managed-by: kubectl
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: django_app
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: django-secret
          command: ["python", "manage.py", "migrate", "--noinput"]